fix(form:array): fix array spanlabelfixed style
ng-alain/delon pull request #1407
Opened 2021-12-24 02:45 UTC by xxx0305102120

修复当设置array widget ui 的spanlabelfixed时，数组小部件的ant-form-item-control-wrapper未按比例显示在同一行内

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ng-alain/delon/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2021-12-28 04:36 UTC, cipchk commented
@xxx0305102120  能否提供一个错误 的 `Schema` 吗？因为 `.ant-form-item-control` 理应包含 `array` 小部件。

2021-12-28 05:11 UTC, xxx0305102120 commented
Schema如下：
```
{
  "properties": {
    "feeCalcTypeName": {
      "type": "string",
      "title": "名称",
      "ui": {
        "widget": "string",
        "placeholder": "名称"
      }
    },
    "feeStages": {
      "type": "array",
      "title": "分段配置",
      "minItems": 1,
      "default": [
        {
          "beginStage": 0,
          "endStage": 0,
          "unitPrice": 0
        }
      ],
      "items": {
        "type": "object",
        "properties": {
          "beginStage": {
            "type": "number",
            "title": "从",
            "ui": {
              "spanLabelFixed": 80,
              "grid": {
                "lg": 24,
                "xl": 24
              }
            }
          },
          "endStage": {
            "type": "number",
            "title": "到",
            "ui": {
              "spanLabelFixed": 80,
              "grid": {
                "lg": 24,
                "xl": 24
              }
            }
          },
          "unitPrice": {
            "type": "number",
            "title": "单价",
            "ui": {
              "widget": "super-number",
              "suffix": "元",
              "spanLabelFixed": 80,
              "grid": {
                "lg": 24,
                "xl": 24
              }
            }
          }
        },
        "ui": {
          "spanLabelFixed": 80,
          "grid": {
            "lg": 24,
            "xl": 24
          }
        },
        "required": [
          "beginStage",
          "endStage",
          "unitPrice"
        ]
      },
      "ui": {
        "optionalHelp": "重量：kg；体积：m³",
        "grid": {
          "arraySpan": 12
        }
      }
    }
  },
  "ui": {
    "spanLabelFixed": 120,
    "grid": {
      "lg": 12,
      "xl": 12,
      "md": 12
    }
  }
}
```

![image](https://user-images.githubusercontent.com/15384445/147530275-1438b721-ee8f-4ddf-ab90-66de433c30ea.png)

![image](https://user-images.githubusercontent.com/15384445/147530350-15df27ee-9b09-4d9f-9cfe-c287054a33c7.png)

2021-12-29 06:03 UTC, cipchk requested changes

2021-12-29 06:03 UTC, cipchk commented on packages/form/src/sf-fixed.directive.ts
> +    const controlEl = widgetEl.querySelector('nz-col.ant-form-item-control-wrapper,.ant-form-item-control');
最好移除 `nz-col.`，它并不是安全，可能会引起无法识别。

2021-12-29 06:10 UTC, xxx0305102120 commented on packages/form/src/sf-fixed.directive.ts
> +    const controlEl = widgetEl.querySelector('nz-col.ant-form-item-control-wrapper,.ant-form-item-control');
好的。

2021-12-29 06:50 UTC, merged